name: Unit Tests

run-name: >
  ${{ github.workflow }}: ${{ github.event_name }} for ${{ github.ref_name }} by @${{ github.actor }}

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  Unit-Tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Pester Tests
        shell: pwsh
        run: |
          $conf = New-PesterConfiguration
          $conf.Run.Path = .\LSEMgmt.Tests.ps1
          $conf.Output.CIFormat = "GithubActions"
          Invoke-Pester -Configuration $conf