name: Publish Module to ACR

run-name: >
  ${{ github.workflow }}: ${{ github.event_name }} for ${{ github.ref_name }} by @${{ github.actor }}

on:
    workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  Publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Register PSResource Repository
        shell: pwsh
        run: |
          Register-PSResourceRepository -Name ${{ vars.PSRepository }} -Uri ${{ vars.PSRepository_URL }} -Trusted:$True

      - name: Publish PowerShell Module
        shell: pwsh
        run: |
          $module = @{
            Path       = '.'
            Repository = ${{ vars.PSRepository }}
          }
          Publish-PSResource @module