name: Publish Module to ACR

run-name: >
  ${{ github.workflow }}: ${{ github.event_name }} for ${{ github.ref_name }} by @${{ github.actor }}

on:
    workflow_dispatch:

jobs:
  Publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
            enable-AzPSSession: true

      - name: Register PSResource Repository
        shell: pwsh
        run: |
          Register-PSResourceRepository -Name ${{ vars.PSRepository }} -Uri ${{ vars.PSRepository_URL }} -Trusted:$True

      - name: Publish PowerShell Module
        shell: pwsh
        run: |
          $module = @{
            Path       = '.'
            Repository = 'ACRDemoRepo'
          }
          Publish-PSResource @module